template bgp dnpeers_extended_hop {
    local as OWNAS;
    path metric on;

    ipv6 {
        import filter import_v6;
        export filter export_v6;
        import limit 9000 action block;
    };

    ipv4 {
        extended next hop;
        import filter import_v4;
        export filter export_v4;
        import limit 9000 action block;
    };
}

include "./peers/extended_hop/*.conf";
