# This is a minimal configuration file, which allows the bird daemon to start
# but will not cause anything else to happen.
#
# Please refer to the documentation in the bird-doc package or BIRD User's
# Guide on http://bird.network.cz/ for more information on configuring BIRD and
# adding routing protocols.

# Change this into your BIRD router ID. It's a world-wide unique identification
# of your router, usually one of router's IPv6 addresses.
#router id 198.51.100.1;

# The Kernel protocol is not a real routing protocol. Instead of communicating
# with other routers in the network, it performs synchronization of BIRD's
# routing tables with the OS kernel.
#protocol kernel {
#	scan time 60;
#	import none;
#	export all;   # Actually insert routes into the kernel routing table
#}

# The Device protocol is not a real routing protocol. It doesn't generate any
# routes and it only serves as a module for getting information about network
# interfaces from the kernel. 
include "./vars.conf";
include "./routes.conf";
function is_self_net_v6()  {
  return net ~ OWNNETSETv6;
}


function is_valid_network_v6()  {
  return net ~ [
    fd00::/8{44,64} # ULA address space as per RFC 4193
  ];
}

roa6 table dn42_roa_v6;

protocol static dn42_roa_v6_proto {
    roa6 { table dn42_roa_v6; };
    include "../../roa/dn42_v6.conf";
};

protocol kernel export_learned_v6 {
    scan time 20;

    ipv6 {
        import none;
        export filter {
            if source = RTS_STATIC then reject;
            krt_prefsrc = OWNIPv6;
            accept;
        };
    };
};

filter reject_self_v6 {
    if net ~ OWNNETSETv6 then reject;
    accept;
}

protocol static import_v6_from_peers {

    ipv6 {
        import filter reject_self_v6;
        export none;
    };
}

filter import_v6 {
          add_proto_communities(proto);
          if is_valid_network_v6() && !is_self_net_v6() then {
            if (roa_check(dn42_roa_v6, net, bgp_path.last) != ROA_VALID) then {
              # Reject when unknown or invalid according to ROA
              print "[dn42] ROA check failed for ", net, " ASN ", bgp_path.last;
              reject;
            } else accept;
          } else reject;
        };

filter export_v6 {
             if !is_valid_network_v6() then reject;

             if source = RTS_STATIC then {
                 bgp_community.add(region);
                 bgp_community.add(country);
                 accept;
             }

             if source = RTS_BGP then {
                 accept;
             }

             reject;
        };

template bgp dnpeers_v6 {
    local as OWNAS;
    path metric on;

    ipv6 {   
        import filter import_v6;
        export filter export_v6;
        import limit 9000 action block;
    };
}

include "../../peers/ipv6/*.conf";
