# This is a basic workflow to help you get started with Actions

name: Deploy Config to Prod

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ${{ inputs.target }}
    name: Copying config to target

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a single command using the runners shell
      - name: Deploying config
        run: cp -r $GITHUB_WORKSPACE/* /etc/bird
  apply-config:
    # The type of runner that the job will run on
    runs-on: ${{ inputs.target }}
    name: Applying Config
    needs: deploy

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      
      - name: Applying Config
        run: birdc configure
